config/routes.rb
Rails.application.routes.draw do
  constraints Clearance::Constraints::SignedIn.new { |user| user.admin? } do
    root to: 'admins#dashboard', as: :admin_dashboard
  end

  constraints Clearance::Constraints::SignedIn.new { |user| user.user? } do
    root to: 'users#dashboard', as: :user_dashboard
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: 'clearance/sessions#new'
  end

  resources :users, only: :create
  resources :admins, only:[]
  resources :items
  resources :orders, only: [:create, :index]
  resources :carts, only: [] do
    post :add_item, on: :collection
    put :update_quantity, param: :cart_item_id # We can place in a new controller selected_item
  end
  get '/cart', to: 'carts#index'
  resources :static, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user

  has_many :cart_items, as: :itemable, class_name: "SelectedItem"
  has_many :items, through: :cart_items, source: :item

  default_scope { includes(:cart_items) }
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, :price, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0}

  scope :by_quantity, -> { order(quantity: :asc) }
  scope :available, -> { where('quantity > ?', 0) }
end

app/models/order.rb
class Order < ApplicationRecord
  validates :user_id, :placed_on, presence: true

  has_many :order_items, as: :itemable, class_name: "SelectedItem"
  has_many :items, through: :order_items
  belongs_to :user

  def total_price
    order_items.inject(0) do |sum, item|
      sum += item.price * item.quantity
      sum
    end
  end
end

app/models/selected_item.rb
class SelectedItem < ApplicationRecord
  belongs_to :itemable, polymorphic: true
  belongs_to :item

  default_scope { includes(:item) }
  delegate :name, :price, to: :item

  validate :check_available_quantity

  def sub_total
    quantity * item.price
  end

  private

  def check_available_quantity
    return true if quantity <= item.quantity
    errors[:base] << 'Number of Items not available in the Inventory' 
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  validates :role_id, presence: true

  enum role_id: [:admin, :user]
  has_one :cart
  has_many :orders
  after_create :create_user_cart

  def place_order
    new_order = orders.create(placed_on: DateTime.now)
    cart.cart_items.each do |selected_item|
      selected_item.itemable = new_order
      selected_item.save
    end
    if Rails.env.development?
      UserMailer.order_confirmation(self, new_order).deliver_now
    end
  end

  private
  def create_user_cart
    self.create_cart
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authorize_admin

  def dashboard
    @items = Item.by_quantity
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
  before_action :require_login

  protected

  def authorize_admin
    unless current_user.admin?
      redirect_to root_path, notice: "You don't have the access to this page."
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def add_item
    item = cart_items.build(cart_item_params)
    flash[:notice] = item.save ? 'Item added successfully' : 'Problem in adding Item to cart'
    redirect_to cart_path
  end

  def update_quantity
    selected_item = SelectedItem.find(params.require(:cart_id))
    if selected_item.update_attributes(update_params)
      redirect_to cart_path, notice: 'Cart updated successfully'
    else
      redirect_to cart_path, notice: selected_item.errors.full_messages.join(', ')
    end
  end

  def index
    @cart_items = cart_items
  end

  private

  def cart_items
    @items ||= current_user.cart.cart_items
  end

  def cart_item_params
    params.permit(:item_id, :price)
  end

  def update_params
    params.require(:selected_item).permit(:quantity)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authorize_admin

  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    if item.save
      redirect_to admin_dashboard_path(), notice: 'Item Created successfully'
    else
      render 'new'
    end
  end

  def edit
    @item = item
  end

  def update
    if item.update_attributes(item_params)
      redirect_to admin_dashboard_path(), notice: 'Item Updated successfully'
    else
      render 'edit'
    end
  end

  def destroy
    item.destroy
    redirect_to admin_dashboard_path(), notice: 'Item Deleted successfully'
  end

  private

  def item_params
    params.require(:item).permit(:name, :price, :image, :quantity)
  end

  def item
    @item ||= Item.find(params.require(:id))
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def create
    current_user.place_order
    redirect_to user_dashboard_path, notice: 'Order placed successfully.'
  end

  private

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

  def dashboard
    @items = Item.available
  end

  private

  def user_params
    params[:user].permit(:email, :password, :full_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def cart_items_count
    current_user.cart.cart_items.count
  end
end

app/views/admins/dashboard.html.erb
<%= link_to "Add Item", new_item_path, class: 'btn btn-success pull-right' %>

<%= render partial: 'items/index', locals: { items: @items } %>

app/views/carts/index.html.erb
<%= link_to "Continue shopping", user_dashboard_path(), class: 'btn btn-success pull-right' %>
<% if @cart_items.count > 0 %>
  <%= link_to "Order Items", orders_path(), method: :post, class: 'btn btn-success pull-right order-btn' %>
<% end %>

<h4>Details of the Cart (<%= @cart_items.count %>)</h4>
<hr/>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>Name of the Item</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Sub Total</th>
    </tr>
  </thead>

  <% @cart_items.each do |cart_item| %>
    <tr>
      <td><%= cart_item.name %></td>
      <td>$<%= cart_item.price %></td>
      <td><%= cart_item.quantity %></td>
      <td>$<%= cart_item.sub_total %></td>
    </tr>
    <tr>
      <%= form_for cart_item, url: cart_update_quantity_path(cart_item.id), method: :put do |f| %>
        <td></td>
        <td></td>
        <td><%= f.text_field :quantity, type: "number", value: cart_item.quantity, class: 'form-control', placeholder: 'No of the Items', required: true, pattern: '^\d+$' %></td>
        <td><%= f.submit 'Update', class: "form-control btn btn-success" %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/items/_form.html.erb
<%= form_for item do |f| %>
  <% if item.errors.present? %>
    <div class='errors'>
      <ul>
        <% item.errors.full_messages.each do |error_message| %>
          <li><%= error_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <label for="name" class="cols-sm-2 control-label">Name <small>*</small></label>
    <div class="form-group">
      <%= f.text_field :name, value: item.name, class: 'form-control', placeholder: 'Name of the Item', required: true, autofocus: true %>
    </div>
  </div>

  <div class="form-group">
    <label for="name" class="cols-sm-2 control-label">Price <small>*</small></label>
    <div class="form-group">
      <%= f.text_field :price, value: item.price, class: 'form-control', placeholder: 'Price of the Item', required: true, pattern: '^\d+(\.\d+)?$' %>
    </div>
  </div>

  <div class="form-group">
    <label for="name" class="cols-sm-2 control-label">Quantity <small>*</small></label>
    <div class="form-group">
      <%= f.text_field :quantity, type: "number", value: item.new_record? ? nil : item.quantity, class: 'form-control', placeholder: 'No of the Items', required: true, pattern: '^\d+$' %>
    </div>
  </div>
  <br/>
  <hr/>

  <div class="form-group">
    <div class="row">
      <div class="col-sm-3 pull-right">
        <%= f.submit item.new_record? ? 'Create' : 'Update', class: "form-control btn btn-success" %>
      </div>
      <div class="col-sm-3 pull-right">
        <%= link_to "Cancel", admin_dashboard_path, class: 'form-control btn btn-default' %>
      </div>
    </div>
  </div>
<% end %>

app/views/items/_index.html.erb
<h4>Items in the Inventory (<%= items.count %>)</h4>
<hr/>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>Name of the Item</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Actions</th>
    </tr>
  </thead>

  <% items.each do |item| %>
    <tr>
      <td><%= item.name %></td>
      <td>$<%= item.price %></td>
      <td><%= item.quantity %></td>
      <td>
        <%= link_to "Edit", edit_item_path(item) %> | 
        <%= link_to "Delete", item_path(item), method: :delete, data: {confirm: 'Are you sure want to delete Item?'} %>
      </td>
    </tr>
  <% end %>
</table>

app/views/items/edit.html.erb
<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <div class='panel'>
      <div class='panel-heading'>
        <h4>Edit Item</h4>
        <hr>
      </div>
      <div class='panel-body'>
        <div class='row'>
          <div class='col-lg-12'>
            <%= render partial: 'items/form', locals: { item: @item } %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel">
      <div class="panel-heading">
        <h4>Create Item</h4>
        <hr>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-12">
            <%= render partial: 'items/form', locals: { item: @item } %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeautifulBasket</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="main_container">
      <div id="body_container">
        <%= render 'shared/header' %>
        <div class="container">
          <%= render 'shared/flash_messages' %>
          <%= yield %>
        </div>
      </div>
      <div id="footer">
        <%= render 'shared/footer' %>
      </div>
    </div>
  </body>
</html>

app/views/orders/index.html.erb
<h4>Details of the Past Orders </h4>
<hr/>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>Order ID</th>
      <th>Plced on</th>
      <th>No of Items</th>
      <th>Total Price</th>
    </tr>
  </thead>

  <% current_user.orders.each do |order| %>
    <tr>
      <td><%= order.id %></td>
      <td><%= order.placed_on.strftime("%m/%d/%Y at %I:%M%p") %></td>
      <td><%= order.order_items.count %></td>
      <td>$<%= order.total_price %></td>
    </tr>
  <% end %>
</table>

app/views/shared/_flash_messages.html.erb
<% if (flash.notice || flash.alert)%>
  <div class='alert alert-info alert-dismissable'>
    <a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a>
    <%= flash[:notice].blank? ? raw(flash[:alert]) : raw(flash[:notice]) %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class='container-fluid text-center' style='background-color: #555; color: white; padding: 10px;'>
  <p>Online Store Copyright</p>
</footer>

app/views/shared/_header.html.erb
<nav class='navbar navbar-inverse'>
  <div class='container-fluid'>
    <div class='container'>
      <div class='navbar-header'>
        <%= link_to 'BeautifulBasket', root_path, class: 'navbar-brand' %>
      </div>
      <div class='collapse navbar-collapse' id='myNavbar'>
        <ul class='nav navbar-nav navbar-right'>
          <% if signed_in? %>
            <li>
              <a href="javascript:void(0);"><%= current_user.email %></a>
            </li>
            <li>
              <%= link_to "Past Orders", orders_path %>
            </li>
            <li>
              <%= link_to "My Cart (#{cart_items_count})", cart_path() %>
            </li>
            <li>
              <%= link_to "Logout", sign_out_path, method: :delete %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/users/_items_list.html.erb
<div class='row'>
  <% items.each do |item| %>
    <div class='col-md-3 col-sm-4 col-xs-12 item-box'>
      <%= image_tag('sample_item.jpg', size: '250x260', alt: 'Item') %>
      Name: <%= item.name %>
      <div class='row'>
        <div class='col-sm-6'>
          Price: <%= item.price %><br/>
          Available: <%= item.quantity %>
        </div>
        <div class='col-sm-6'>
          <% if current_user.cart.items.include?(item) %>
            <%= link_to "Remove", 'javascript:void(0)', method: :post, class: 'btn btn-default' %>
          <% else %>
            <%= link_to "Add to Cart", add_item_carts_path(item_id: item.id, price: item.price), method: :post, class: 'btn btn-success' %>
          <% end %>
        </div>
      </div>
      <hr/>
    </div>
  <% end %>
</div>

app/views/users/dashboard.html.erb
<%= render partial: 'users/items_list', locals: { items: @items } %>

app/views/users/new.html.erb
<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <div class='panel panel-login'>
      <div class='panel-heading'>
        <h4>Registration</h4>
        <hr>
      </div>
      <div class='panel-body'>
        <div class='row'>
          <div class='col-lg-12'>
            <%= form_for @user do |f| %>
              <% if @user.errors.present? %>
                <div class='errors'>
                  <ul>
                    <% @user.errors.full_messages.each do |error_message| %>
                      <li><%= error_message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
              <div class='form-group'>
                <label for='name' class='cols-sm-2 control-label'>Full Name</label>
                <div class='form-group'>
                  <%= f.text_field :full_name, class: 'form-control', placeholder: 'Full Name' %>
                </div>
              </div>
              <div class='form-group'>
                <label for='name' class='cols-sm-2 control-label'>Email</label>
                <div class='form-group'>
                  <%= f.text_field :email, type: 'email', class: 'form-control', placeholder: 'Email' %>
                </div>
              </div>
              <div class='form-group'>
                <label for='name' class='cols-sm-2 control-label'>Password</label>
                <div class='form-group'>
                  <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
                </div>
              </div>
              <hr/>
              <div class='form-group'>
                <div class='row'>
                  <div class='col-sm-6 col-sm-offset-3'>
                    <%= f.submit 'Create Account', class: 'form-control btn btn-success' %>
                  </div>
                </div>
              </div>
              <div class='form-group'>
                <div class='row'>
                  <div class='col-lg-12'>
                    <div class='text-center'>
                      <%= link_to 'Login', sign_in_path %>&nbsp;|
                      <%= link_to 'Forgot Password?', new_password_path %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>